### PR TITLE
Correctly concat base url

### LINKED ISSUE #3: Result item final url isn't correct
My base url is: `https://company.atlassian.net/wiki` and an example `href` from a search result is: `https://company.atlassian.net/wiki/spaces/ENG/pages/18819411/Knowledge+-+prototype+basics`

This means when the code concats these together you get a bad url with `https://company.atlassian.net/wik/wiki/...` which leads to a 404.

The correct way to join them is to grab the http scheme and domain and concat that with the href received from Atlassian search result. This is the way the python workflow does it: https://github.com/skleinei/alfred-confluence/blob/f992894d21525150e54ee1da90a01931b0364e09/src/alfred-confluence.py#L173-L176

Anyway many thanks for the workflow and the work on fixing issues

### PR DESCRIPTION
**Pull request by pgilad**
fixes #3

### CODE REVIEW

**Comment by pgilad** [comment]
Ping @jovobe

**Comment by jovobe** [comment]
Thanks for your contribution! This would not work for cloud versions, right? The base URL in cloud version is e.g. https://jovobe.atlassian.net/wiki and the `/wiki` part is required.

**Comment by pgilad** [comment]
The current version of this workflow doesn't work for the cloud version, right. I implemented the same solution as the Python workflow where now the base_url is used entirely for getting the results, but only the netloc (scheme + domain) is concated to the results href to form the link to the results. (See https://github.com/skleinei/alfred-confluence/blob/master/src/alfred-confluence.py#L173-L176)

**Comment by pgilad** [comment]
@jovobe any plans to merge this?

**Comment by jovobe** [comment]
@pgilad absolutely! Unfortunately, I don't have time right now. I will take care of it next week.

**Comment by jovobe** [comment]
Thank you so much for your contribution @pgilad! I finally found time to check this, and it looks all good 👍🏻

**Pull request merged**
